# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: my gpt-5
    provider: openai
    model: gpt-5
    apiKey: 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
  - name: qwen2.5-coder 7b
    provider: ollama
    model: qwen2.5-coder:7b
    roles:
      - apply
      - autocomplete
      - chat
      - edit
  - name: Claude 4 Sonnet
    provider: anthropic
    model: claude-sonnet-4-20250514
    apiKey: ${{ secrets.ANTHROPIC_API_KEY }}
    roles:
      - chat
      - edit
      - apply
    defaultCompletionOptions:
      contextLength: 200000
      maxTokens: 64000
    capabilities:
      - tool_use
      - image_input
