package com.hst.entity.BookingSys;
public enum BookingStatus {
    PENDING,
    CONFIRMED,
    CHECKED_IN,
    COMPLETED,
    CANCELLED,
    PENDING_PAYMENT,
    PAYMENT_FAILED,
    PAYMENT_SUCCESS,
    PAYMENT_REFUNDED,
    PAYMENT_PENDING,
    PAYMENT_CANCELLED,
    PAYMENT_PROCESSING,
    PAYMENT_TIMEOUT,
    PAYMENT_DECLINED,
    PAYMENT_ERROR,
    PAYMENT_REVERSED,
    PAYMENT_DISPUTED,
    PAYMENT_RECIVED_AWAITING_CONFIRMATION
}
